server.port: 9090
spring.datasource.url: jdbc:mysql://localhost:3306/homeexchange
spring.datasource.username: root
spring.datasource.password: P@ssw0rd
spring.datasource.driver.class: com.mysql.jdbc.Driver.class
com.homeswap.jwtSecret: bezKoderSecretKey
com.homeswap.jwtExpirationMs : 86400000
spring.jpa.hibernate.ddl-auto: update
spring:  resources:    static-locations:    - file:///classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:///C:/images/


